# see http://www.scons.org/wiki/Qt4Tool
#     https://launchpad.net/scons-qt4

# untar scons-qt4-0.2.tar.gz into site_scons/site_tools

Import ('env')

env.Tool ('qt4')
env.EnableQt4Modules (["QtGui", "QtCore"])

sources = ['main.cpp',
           'MainWindow.cpp',
           'ImageViewPair.cpp',
           'ImageView.cpp',
           'SauvolaControls.cpp',
           'IntControl.cpp',
           'DoubleControl.cpp']

libs = ['/usr/lib64/libqwt.so']
# $$$ better way to find libqwt?

env.Program ('binarize', sources + libs)

